import { ThemeContextProvider } from "@/context/ThemeContext";
import "./globals.css";
import { Montserrat } from "next/font/google";
import MyThemeProvider from "@/providers/ThemeProvider";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  description: "Generated by create next app", // description is optional here
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Hassan Iqbal</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <ThemeContextProvider>
          <MyThemeProvider>{children}</MyThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
